# Generated by Django 5.1.1 on 2024-09-24 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0002_userprofile_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile_table',
            old_name='Name',
            new_name='name',
        ),
    ]
