# Generated by Django 5.1.1 on 2024-09-24 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0003_rename_name_userprofile_table_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile_table',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_dashboard.user_table'),
        ),
    ]
