# Generated by Django 5.1.1 on 2024-10-01 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0006_land'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='land',
            name='land_name',
        ),
    ]
