# Generated by Django 5.1.1 on 2024-10-01 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0007_remove_land_land_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='land',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='land',
            name='longitude',
        ),
    ]
